language:
  - swift
osx_image: xcode10.2
script:
  -xcodebuild test -project foodDelivery/foodDelivery.xcodeproj  -scheme foodDelivery -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 8' 
